config/routes.rb
Committees::Application.routes.draw do
  resources :committees, :only => [:index, :show]
  resources :nominations, :only => [:new, :create]
  resources :applications, :only => [:new, :create] 
  
  devise_for :users

  #   match 'products/:id' => 'catalog#view'

  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase

  #   resources :products

  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  namespace :admin do
    resources :users, :only => [:index, :new, :create, :destroy]
    resources :sections
    resources :committees
    resources :content, :only => [:index, :edit, :update]
    resources :questions, :only => [:index, :new, :create, :destroy]
    resources :nominations, :only => [:index, :show, :edit, :update, :destroy]
    root :to => 'committees#index', :as => ""
  end



  root :to => 'main#index'

end

app/models/section.rb
class Section < ActiveRecord::Base
  validates :name, :presence => true
  has_many :committees
end

app/controllers/admin/sections_controller.rb
class Admin::SectionsController < Admin::BaseController 
  load_and_authorize_resource :section
  respond_to :html
  def index
    respond_with(@sections)
  end

  def show
    respond_with(@section)
  end

  def new
    respond_with(@section)
  end

  def create
    @section.save
    respond_with(@section, :location => admin_sections_path)
  end

  def edit
    respond_with(@section)
  end

  def update
    @section.update_attributes(params[:section])
    respond_with(@section)
  end

  def destroy
    @section.destroy
    respond_with(@section)
  end

end

app/helpers/admin/sections_helper.rb
module Admin::SectionsHelper
end

app/views/admin/sections/_form.html.haml
= simple_form_for([:admin, @section]) do |f|
  = f.input :name
  = f.input :info
  = f.button :submit

app/views/admin/sections/edit.html.haml
- title "Editing #{@section.name}"
= render 'form'

app/views/admin/sections/index.html.haml
- title "Manage Sections"
= link_to "Create Section", new_admin_section_path, :class => "btn primary"
%table.committees.zebra-striped
  %thead
    %tr
      %th Name
      %th Action
  %tbody
    - @sections.each do |section|
      %tr
        %td= link_to section.name, admin_section_path(section)
        %td
          = link_to "Edit", edit_admin_section_path(section)
          = link_to "Delete", admin_section_path(section), :method => "delete", :confirm => "Are you sure you want to delete this section? Maybe you should just rename it?"

app/views/admin/sections/new.html.haml
- title "New Section"
= render 'form'

app/views/admin/sections/show.html.haml
- title @section.name
= markdown(@section.info)