config/routes.rb
Committees::Application.routes.draw do
  resources :committees, :only => [:index, :show]
  resources :nominations, :only => [:new, :create]
  resources :applications, :only => [:new, :create] 
  
  devise_for :users

  #   match 'products/:id' => 'catalog#view'

  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase

  #   resources :products

  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  namespace :admin do
    resources :users, :only => [:index, :new, :create, :destroy]
    resources :sections
    resources :committees
    resources :content, :only => [:index, :edit, :update]
    resources :questions, :only => [:index, :new, :create, :destroy]
    resources :nominations, :only => [:index, :show, :edit, :update, :destroy]
    root :to => 'committees#index', :as => ""
  end



  root :to => 'main#index'

end

app/models/committee.rb
class Committee < ActiveRecord::Base
  attr_accessible :name, :info, :contact_info, :website, :section_id, :section, :use_default_questions, :applications_open
  
  belongs_to :section
  default_scope includes(:section)

  has_many :nominations
  has_many :nominees, :through => :nominations, :uniq => true
  has_many :applications
  has_many :applicants, :through => :applications

  def nominees_and_applicants
    @n_and_a ||= (self.nominees + self.applicants).uniq
  end

  def nominations_for(nominee)
    self.nominations.find_all_by_nominee_id(nominee.id)
  end

  def nominators_for(nominee)
    self.nominations_for(nominee).map(&:nominator).map(&:name).join(", ")
  end

  def application_for(applicant)
    self.applications.find_by_applicant_id(applicant.id)
  end

  def date_for(nominee)
     (nominations_for(nominee) + [application_for(nominee)] ).compact.map(&:updated_at).max
  end
end

app/controllers/admin/committees_controller.rb
class Admin::CommitteesController < Admin::BaseController  
  load_and_authorize_resource
  def index
    Committee.find(:all, :include => :section, :order => "sections.id DESC")
    respond_with(@committee)
  end

  def new
    respond_with(@committee)
  end

  def create
    @committee = Committee.create(params[:committee])
    respond_with(@committee, :location => admin_committees_path)
  end

  def edit
    respond_with(@committee)
  end

  def update
    @committee.update_attributes(params[:committee])
    respond_with(@committee, :location => admin_committees_path)
  end

  def destroy
    @committee.destroy
    respond_with(@committee)
  end

  def show
    respond_with(@committee)
  end


end

app/controllers/committees_controller.rb
class CommitteesController < ApplicationController
  
  def index
    if params[:section_id]
      @section = Section.find(params[:section_id])
      @committees =  Committee.find_all_by_section_id(params[:section_id])
    elsif params[:section_type] == "open"
      @section = Section.new(name: "Open for Applications")
      @committees = Committee.find_all_by_applications_open(true)
    else
      @section = Section.new(name: "Other")
      @committees = Committee.find_all_by_section_id(nil)      
    end
  end
  def show
    @committee = Committee.find(params[:id])
  end

end

app/helpers/admin/committees_helper.rb
module Admin::CommitteesHelper
end

app/helpers/committees_helper.rb
module CommitteesHelper
end

app/views/committees/_committee.html.haml
%h2= committee.name 
- if committee.applications_open
  = link_to "Nominate for Committee", new_nomination_path(:committee_id => committee.id), :class => "btn large primary" 
  = link_to "Apply to Committee", new_application_path(:committee_id => committee.id), :class => "btn large primary"
- else
  Applications to this committee are not open at this time.
%p= markdown(committee.info)
- unless committee.contact_info.blank?
  %p 
    %em Contact:
    = markdown(committee.contact_info)
- unless committee.website.blank?
  %p
    %em Website:
    %p= link_to committee.website, committee.website

app/views/committees/index.html.haml
- title @section.name
= markdown(@section.info)

- @committees.each do |committee|
  = render "committee", :committee => committee

app/views/committees/show.html.haml
- title @committee.name 
%p= markdown(@committee.info)
- unless @committee.contact_info.blank?
  %p 
    %strong Contact:
    = markdown(@committee.contact_info)
- unless @committee.website.blank?
  %p
    %em Website:
    %p= link_to @committee.website, @committee.website

= link_to "Nominate for Committee", new_nomination_path(:committee_id => @committee.id), :class => "btn large primary" 

= link_to "Apply to Committee", new_application_path(:committee_id => @committee.id), :class => "btn large primary"