config/routes.rb
Committees::Application.routes.draw do
  resources :committees, :only => [:index, :show]
  resources :nominations, :only => [:new, :create]
  resources :applications, :only => [:new, :create] 
  
  devise_for :users

  #   match 'products/:id' => 'catalog#view'

  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase

  #   resources :products

  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  namespace :admin do
    resources :users, :only => [:index, :new, :create, :destroy]
    resources :sections
    resources :committees
    resources :content, :only => [:index, :edit, :update]
    resources :questions, :only => [:index, :new, :create, :destroy]
    resources :nominations, :only => [:index, :show, :edit, :update, :destroy]
    root :to => 'committees#index', :as => ""
  end



  root :to => 'main#index'

end

app/controllers/admin/content_controller.rb
class Admin::ContentController < Admin::BaseController
  def index
    @items = SiteContent.all
    respond_with(@items)
  end

  def edit
    @item = SiteContent.find(params[:id])
    respond_with(@item)
  end

  def update
    @item = SiteContent.find(params[:id])
    @item.update_attributes(params[:site_content])
    respond_with(@item, :location => admin_content_index_path)
  end
end

app/views/admin/content/edit.html.haml
%h1= "Editing #{@item.name}"
%h3= @item.description

The text is written in a markup language known as Markdown. See 
%a(href="http://daringfireball.net/projects/markdown/syntax" target="_blank")
  the documentation
for details.

= simple_form_for(@item, :url => admin_content_path, :method => :put) do |f|
  = f.input :text
  = f.submit

app/views/admin/content/index.html.haml
- title "Manage Site Content" 
%table.committees.zebra-striped
  %thead
    %tr
      %th Name
      %th Description
      %th Action
  %tbody
    - @items.each do |item|
      %tr
        %td= item.name
        %td= item.description
        %td
          = link_to "Edit", edit_admin_content_path(item)