config/routes.rb
Committees::Application.routes.draw do
  resources :committees, :only => [:index, :show]
  resources :nominations, :only => [:new, :create]
  resources :applications, :only => [:new, :create] 
  
  devise_for :users

  #   match 'products/:id' => 'catalog#view'

  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase

  #   resources :products

  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  namespace :admin do
    resources :users, :only => [:index, :new, :create, :destroy]
    resources :sections
    resources :committees
    resources :content, :only => [:index, :edit, :update]
    resources :questions, :only => [:index, :new, :create, :destroy]
    resources :nominations, :only => [:index, :show, :edit, :update, :destroy]
    root :to => 'committees#index', :as => ""
  end



  root :to => 'main#index'

end

app/views/layouts/_scripts.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-28580402-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/layouts/admin.html.haml
- content_for :sidebar do
  %h2 Admin Panel
  %ul.unstyled
    %li= link_to "Manage Site Content", admin_content_index_path
    %li= link_to "Manage Admins", admin_users_path
    %li= link_to "Manage Sections", admin_sections_path
    %li= link_to "Manage Committees", admin_committees_path
    %li= link_to "Manage Questions", admin_questions_path
= render :template => 'layouts/application'

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= "#{title} | UChicago Committees" 
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = javascript_include_tag "http://sg.uchicago.edu/sg-header/sg-header.js"
    = render "layouts/scripts"
    = csrf_meta_tags
  %body
    .page-header
      .user-panel
        - if current_user
          = "Welcome, #{current_user.username}"
          - if current_user.is_admin
            = link_to "Admin Panel", admin_path
            = " | "
          = link_to "Logout", destroy_user_session_path, :method => "delete"
        - else
          = link_to "Login", new_user_session_path

    .container-fluid
      .header
        = link_to "http://sg.uchicago.edu/" do 
          = image_tag "sg.jpg", :class => 'logo'
        = link_to root_path do
          %h1 UChicago Committees
        %p 
          Looking to join one of the University's many Student Life Committees?
          %br 
          You've come to the right place!  
      .sidebar
        - if content_for?(:sidebar)
          = yield :sidebar
        - else
          %ul.committees.unstyled
            %li= link_to "OPEN", committees_path(:section_type => "open")
            - Section.all.each do |section|
              %li= link_to section.name, committees_path(section_id: section.id)
            - if Committee.count(:conditions => {:section_id => nil }) > 0
              %li= link_to "Other", committees_path
      
      .content
        %h1= title
        
        .flashes
          - flash.each do |type, text|
            %div{"class" => "#{type} alert-message"}= text
        .row
          .span10.columns
            = yield